--- 
kind: pipeline
type: docker
name: "Helm Charts"
steps: 
  -
    commands:
      - "ct lint --config ct.yaml --all"
    image: "quay.io/helmpack/chart-testing:v3.0.0-rc.1"
    name: "Chart Testing"
  - 
    commands: 
      - "mkdir -p ./public"
      - "cd public"
      - |-
          echo "User-Agent: *
          Disallow: /" > robots.txt
      - "echo \"<h1>PetriPod Charts</h1>\" > index.html"
      - "helm package ../charts/* --destination ."
      - "helm repo index --url https://charts.petripod.dev ."
    image: "alpine/helm:3.2.4"
    name: "Package Charts"
  - 
    image: plugins/gh-pages
    name: "Publish Charts"
    settings: 
      pages_directory: public/
      password: 
        from_secret: github_secret
      username: 
        from_secret: github_username
